
# Setup
title:               SGSC
email:               sgsc@gateofsci.com
tagline:             Science Gateway Software and Consultation
url:                 "" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              SGSC
  url:               
  email:             sgsc@gateofsci.com

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: sciencegateway
twitter_username: 
instagram_username: 
facebook: 
linkedin_username: 
dribbble_username: 

# Custom vars
version:    
github:
  repo:     

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
